networks:
  energy-lab-net:
    driver: bridge

services:
  #Shared telemetry store
  redis:
    image: redis:7
    container_name: redis
    networks:
      - energy-lab-net

  # Data Center A (High Emission / Fossil Fuel)
  dc-a:
    build:
      context: .
      dockerfile: dc_server/Dockerfile
    container_name: dc-a
    environment:
      - REGION=dc-a
      - CARBON_INTENSITY=450
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    networks:
      - energy-lab-net

  # Data Center B (Medium Emission / Mixed Grid)
  dc-b:
    build:
      context: .
      dockerfile: dc_server/Dockerfile
    container_name: dc-b
    environment:
      - REGION=dc-b
      - CARBON_INTENSITY=220
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    networks:
      - energy-lab-net

  # Data Center C (Low Emission / 100% Renewable)
  dc-c:
    build:
      context: .
      dockerfile: dc_server/Dockerfile
    container_name: dc-c
    environment:
      - REGION=dc-c
      - CARBON_INTENSITY=15
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    networks:
      - energy-lab-net

  # Client sending QUIC packets
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    environment:
      - TARGET_HOST=dc-a
      - TARGET_PORT=4433
      - PYTHONUNBUFFERED=1
    networks:
      - energy-lab-net
    depends_on:
      - dc-a
      - dc-b
      - dc-c
